'use strict';

angular.module('odssPlatimApp', [
    'ui.bootstrap',
    'ngSanitize',
    'odssPlatimApp.model',
    'odssPlatimApp.platform',
    'odssPlatimApp.token',
    'odssPlatimApp.period',
    'odssPlatimApp.util',
    'odssPlatimApp.services',
    'odssPlatimApp.templates', // generated by `grunt ngtemplates`
    'odssPlatimApp.main'
]);
